# Generated by Django 5.1.7 on 2026-08-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropietarioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('barrio', models.CharField(blank=True, max_length=20)),
                ('avenida', models.CharField(blank=True, max_length=20)),
                ('nro_inmueble', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Informacion del Propietario',
                'verbose_name_plural': 'Informacion del Propietario',
            },
        ),
    ]
